-- CreateEnum
CREATE TYPE "MatchStatus" AS ENUM ('PENDING', 'ACCEPTED', 'REJECTED');

-- AlterTable
ALTER TABLE "user_type_scores" ALTER COLUMN "cleanliness" SET DEFAULT 0.0,
ALTER COLUMN "cleanliness" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "noise" SET DEFAULT 0.0,
ALTER COLUMN "noise" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "sharedItems" SET DEFAULT 0.0,
ALTER COLUMN "sharedItems" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "communication" SET DEFAULT 0.0,
ALTER COLUMN "communication" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "sleepPattern" SET DEFAULT 0.0,
ALTER COLUMN "sleepPattern" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "patience" SET DEFAULT 0.0,
ALTER COLUMN "patience" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "attention" SET DEFAULT 0.0,
ALTER COLUMN "attention" SET DATA TYPE DOUBLE PRECISION;

-- CreateTable
CREATE TABLE "MatchRequest" (
    "id" SERIAL NOT NULL,
    "senderId" INTEGER NOT NULL,
    "receiverId" INTEGER NOT NULL,
    "status" "MatchStatus" NOT NULL DEFAULT 'PENDING',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "MatchRequest_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "MatchRequest" ADD CONSTRAINT "MatchRequest_senderId_fkey" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MatchRequest" ADD CONSTRAINT "MatchRequest_receiverId_fkey" FOREIGN KEY ("receiverId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
